git clone ... recurse-submodules to get pydal
carl@twist:~/src/web2py$ python web2py.py
Traceback (most recent call last):
  File "web2py.py", line 18, in <module>
    import gluon.widget
  File "/home/carl/src/web2py/gluon/__init__.py", line 29, in <module>
    "You can also download a complete copy from http://www.web2py.com."
RuntimeError: web2py depends on pydal, which apparently you have not installed.
Probably you cloned the repository using git without '--recursive'
To fix this, please run (from inside your web2py folder):

     git submodule update --init --recursive

You can also download a complete copy from http://www.web2py.com.